const ActionTypes = {
  INITIALIZE: 'INITIALIZE',
  ON_PORT_UPDATE: 'ON_PORT_UPDATE',
  SORT: 'SORT',
  CLICK_GROUP_ROW: 'CLICK_GROUP_ROW',
  CLOSE_PORTS: 'CLOSE_PORTS',
};

export default ActionTypes;
