const ActionTypes = {
  INITIALIZE: 'INITIALIZE',
  ON_PORT_UPDATE: 'ON_PORT_UPDATE',
  SORT: 'SORT',
  ON_SELECT_GROUP: 'ON_SELECT_GROUP',
  CLOSE_PORTS: 'CLOSE_PORTS',
};

export default ActionTypes;
